### ISSUE TITLE
Detail on configuration

### ISSUE THREAD

**Issue by spences10** [bahmutov/now-pipeline#25]
Hi @bahmutov,

Thank so much for this, I was hoping to find something for CI so I didn't have to install Ruby, `now-pipeline` appears to be it 😀👍 

I'm still pretty noob when it comes to this sort of thing so was wondering if you could explain/give a bit more detail on set up.

I have installed `npm i -g now-pipeline` on my machine, I'm guessing now at the time of writing this that there's probably not much use in that if the package is being installed on Travis 🙃 

I have my blog which I'd like to set up for use with Travis, so I've enabled it on [Travis CI] and added in the new environment variable from my [Zeit dashboard]

![image](https://user-images.githubusercontent.com/234708/34650894-325c30a8-f3c0-11e7-9397-572da4a18f91.png)

Then I've set up my `.travis.yml` with some of the examples from your `README.md` now I thought I could run `now-pipeline` from my terminal, but I'm guessing it happens on Travis, right?

[travis ci]: https://travis-ci.org
[zeit dashboard]: https://zeit.co/account/tokens

**Comment by bahmutov** [comment]
Not from the terminal - when you are working locally you can always do `now`. This deploys from your local machine to a unique url, but nothing else. From travis, you run `now-pipeline` and it deploys (from CI machine), runs tests (optional), switches DNS alias to point at the new deployment, cleans up old deploys.

So your travis file would look something like this

```
script:
  - npm install -g now-pipeline
  - now-pipeline
```

Every time you push to your GitHub repo, travis gets notified, it runs the test job and executes `now-pipeline`

**Comment by spences10** [comment]
Will you accept a PR with some more details in the README.md?

**Comment by bahmutov** [comment]
Sure!

**Comment by spences10** [comment]
I'll submit a PR when I manage to get it working, closing this.
