### ISSUE TITLE
If `now-pipeline` succeeds should I be able to `now ls` from my terminal to see the deployed URL?

### ISSUE THREAD

**Issue by spences10** [bahmutov/now-pipeline#27]
Travis CI gives `The command "now-pipeline" exited with 0.` but using `now ls` doesn't display any new URLs, there should be something there if there's no errors, right?

**Comment by bahmutov** [comment]
hmm, seems like a bug, or the deploy did not really happen

**Comment by bahmutov** [comment]
Can you see any debug messages while it is deploying? Set environment variable on Travis (or run the tool locally) https://github.com/bahmutov/now-pipeline#debugging

**Comment by spences10** [comment]
I have been debugging my Gatsby build for best part of the morning now actually @bahmutov 😁 

I'll come to this once I have a clean build running 👌 

Thanks for all the support, appreciate it 😀

**Comment by bahmutov** [comment]
Ok, I just tested using this project https://github.com/bahmutov/todomvc-express
and it passed, deployed https://travis-ci.org/bahmutov/todomvc-express and I can see the url using `now ls`
```
todomvc-express (1 of 1 total)
 url                                                     inst #    state                 age
 todomvc-express-oksygzehct.now.sh                            1    READY                  4m
```
